"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { AdminWebinarRegistrationRow, AdminWebinarRow } from "../_lib/admin-types";
import { AdminCard, AdminCopyButton, AdminErrorState, AdminLoadingState, AdminMetric, AdminPageHeader, AdminStatusBadge, formatDateTime } from "./admin-ui";

export function AdminWebinarDetail({ webinarId }: { webinarId: string }) { const [webinar, setWebinar] = useState<AdminWebinarRow | null>(null); const [registrations, setRegistrations] = useState<AdminWebinarRegistrationRow[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { const [w, r] = await Promise.all([supabase.from("webinars").select("*").eq("id", webinarId).single(), supabase.from("webinar_registrations").select("id, first_name, last_name, email, business_type, annual_birds_sold, referral_source, attended, created_at").eq("webinar_id", webinarId).order("created_at", { ascending: false })]); if (w.error || r.error) setError(w.error?.message ?? r.error?.message ?? "Could not load webinar."); else { setWebinar(w.data as AdminWebinarRow); setRegistrations((r.data ?? []) as AdminWebinarRegistrationRow[]); } setLoading(false); })(); }, [webinarId]);
  const exportCsv = () => { if (!webinar) return; const headers = ["Webinar title", "Webinar date", "First name", "Last name", "Email", "Business type", "Annual birds sold", "Referral source", "Attended", "Registered at"]; const rows = registrations.map((r) => [webinar.title, formatDateTime(webinar.starts_at), r.first_name, r.last_name, r.email, r.business_type, r.annual_birds_sold, r.referral_source ?? "", r.attended ? "Yes" : "No", formatDateTime(r.created_at)]); const csv = [headers, ...rows].map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = `${webinar.slug}-registrations.csv`; link.click(); URL.revokeObjectURL(link.href); };
  async function setAttended(id: string, attended: boolean) { const { error: updateError } = await supabase.from("webinar_registrations").update({ attended }).eq("id", id); if (updateError) { setError(updateError.message); return; } setRegistrations((current) => current.map((row) => row.id === id ? { ...row, attended } : row)); }
  const attendedCount = useMemo(() => registrations.filter((row) => row.attended).length, [registrations]);
  if (loading) return <div className="p-5"><AdminLoadingState label="Loading webinar" /></div>; if (error || !webinar) return <div className="p-5"><AdminErrorState message={error ?? "Webinar not found."} /></div>;
  const publicUrl = `https://www.flockfront.com/webinars/${webinar.slug}`;
  return <><AdminPageHeader eyebrow="Webinar" title={webinar.title} description={webinar.short_description} action={<div className="flex gap-2"><Link className="seller-secondary-button" href={`/webinars/${webinar.slug}`} target="_blank">Open public page</Link><Link className="seller-primary-button" href={`/admin/webinars/${webinar.id}/edit`}>Edit</Link></div>} /><div className="mx-auto grid w-full max-w-7xl gap-5 px-5 py-5 sm:px-7"><div className="grid gap-3 sm:grid-cols-3"><AdminMetric label="Registrations" value={registrations.length} /><AdminMetric label="Attended" value={attendedCount} /><AdminMetric label="Date" value={formatDateTime(webinar.starts_at)} /></div><AdminCard><div className="flex flex-wrap items-center justify-between gap-3 border-b border-stone-200 p-4"><div><AdminStatusBadge value={webinar.status} /><div className="mt-2 flex flex-wrap items-center gap-2 text-sm"><span className="font-semibold text-stone-700">Public URL:</span><a className="break-all text-[#17613a] underline underline-offset-2" href={publicUrl} target="_blank">{publicUrl}</a><AdminCopyButton label="Copy link" value={publicUrl} /></div></div><button className="seller-secondary-button" type="button" onClick={exportCsv}>Export CSV</button></div>{registrations.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#f7faf8] text-xs uppercase tracking-wide text-stone-600"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Business type</th><th className="px-4 py-3">Annual birds</th><th className="px-4 py-3">Referral</th><th className="px-4 py-3">Registered</th><th className="px-4 py-3">Attended</th></tr></thead><tbody className="divide-y divide-stone-200">{registrations.map((row) => <tr key={row.id}><td className="px-4 py-3 font-semibold">{row.first_name} {row.last_name}</td><td className="px-4 py-3">{row.email}</td><td className="px-4 py-3">{row.business_type}</td><td className="px-4 py-3">{row.annual_birds_sold}</td><td className="px-4 py-3">{row.referral_source || "—"}</td><td className="px-4 py-3 whitespace-nowrap">{formatDateTime(row.created_at)}</td><td className="px-4 py-3"><input aria-label={`Attended: ${row.first_name} ${row.last_name}`} checked={row.attended} onChange={(event) => void setAttended(row.id, event.target.checked)} type="checkbox" /></td></tr>)}</tbody></table></div> : <p className="p-5 text-sm text-stone-600">No registrations yet.</p>}</AdminCard></div></>;
}
