import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { publicSupabase } from "@/lib/public-supabase";
import { WebinarRegistrationForm } from "./registration-form";

type PublicWebinar = { id: string; title: string; slug: string; short_description: string; starts_at: string; timezone: string };

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const { data } = await publicSupabase.rpc("get_public_webinar", { p_slug: slug }).maybeSingle(); const webinar = data as PublicWebinar | null; return { title: webinar ? `${webinar.title} | FlockFront` : "Webinar | FlockFront", description: webinar?.short_description ?? "FlockFront webinar registration" }; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const { data, error } = await publicSupabase.rpc("get_public_webinar", { p_slug: slug }).maybeSingle(); const webinar = data as PublicWebinar | null; if (error || !webinar) notFound(); return <main className="min-h-screen bg-[#fffaf1] text-[#10281c]"><div className="mx-auto max-w-6xl px-5 py-5 sm:px-8"><header className="flex items-center justify-between border-b border-[#dce5dc] pb-5"><a href="/"><Image alt="FlockFront" height={236} src="/branding/flockfront-logo-final-cropped.png" width={1549} className="h-auto w-44" /></a><p className="hidden text-sm sm:block">Questions? Email us at <a className="font-semibold text-[#17613a]" href="mailto:hello@flockfront.com">hello@flockfront.com</a></p></header><section className="mx-auto max-w-4xl py-12 text-center"><span className="inline-flex rounded-full bg-[#e6f0e8] px-4 py-2 text-sm font-bold uppercase tracking-wide text-[#17613a]">Live Webinar</span><h1 className="mt-6 text-balance font-serif text-4xl font-bold leading-tight text-[#10281c] sm:text-6xl">{webinar.title}</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#59635d]">{webinar.short_description}</p><p className="mt-5 text-base font-semibold text-[#17613a]">{new Intl.DateTimeFormat("en-US", { dateStyle: "full", timeStyle: "short", timeZone: webinar.timezone }).format(new Date(webinar.starts_at))} ({webinar.timezone})</p><div className="mx-auto mt-10 max-w-2xl rounded-2xl bg-white p-6 text-left shadow-[0_8px_24px_rgba(45,35,20,0.09)] ring-1 ring-stone-200 sm:p-9"><h2 className="text-center text-2xl font-bold">Register for the webinar</h2><p className="mt-2 text-center text-sm text-[#59635d]">Save your seat and we’ll send the join link to your inbox.</p><WebinarRegistrationForm slug={slug} /></div></section></div><footer className="bg-[#0f542f] px-5 py-8 text-white"><div className="mx-auto flex max-w-6xl items-center gap-4"><Image alt="FlockFront" height={236} src="/branding/flockfront-logo-final-cropped.png" width={1549} className="w-36 brightness-0 invert" /><span className="border-l border-white/40 pl-4 text-sm">The all-in-one platform for poultry sellers.</span></div></footer></main>; }
