import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { publicSupabase } from "@/lib/public-supabase";
import { WebinarRegistrationForm } from "./registration-form";

type PublicWebinar = { id: string; title: string; slug: string; short_description: string; starts_at: string; timezone: string };

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const { data } = await publicSupabase.rpc("get_public_webinar", { p_slug: slug }).maybeSingle(); const webinar = data as PublicWebinar | null; return { title: webinar ? `${webinar.title} | FlockFront` : "Webinar | FlockFront", description: webinar?.short_description ?? "FlockFront webinar registration" }; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const { data, error } = await publicSupabase.rpc("get_public_webinar", { p_slug: slug }).maybeSingle(); const webinar = data as PublicWebinar | null; if (error || !webinar) notFound(); const webinarDate = formatWebinarDate(webinar.starts_at, webinar.timezone); return <main className="min-h-screen bg-[#fffaf1] text-[#10281c]"><div className="mx-auto max-w-5xl px-5 py-4 sm:px-8"><header className="flex items-center justify-between border-b border-[#dce5dc] pb-4"><a href="/"><Image alt="FlockFront" height={236} src="/branding/flockfront-logo-final-cropped.png" width={1549} className="h-auto w-40 sm:w-44" /></a><p className="hidden text-sm sm:block">Questions? Email us at <a className="font-semibold text-[#17613a]" href="mailto:hello@flockfront.com">hello@flockfront.com</a></p></header><section className="mx-auto max-w-3xl py-7 text-center sm:py-9"><span className="inline-flex rounded-full bg-[#e6f0e8] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-[#17613a]">Live Webinar</span><h1 className="mt-3 text-balance font-serif text-3xl font-bold leading-tight text-[#10281c] sm:text-5xl">{webinar.title}</h1><p className="mx-auto mt-3 max-w-2xl text-base leading-7 text-[#59635d] sm:text-lg">{webinar.short_description}</p><div className="mx-auto mt-4 flex max-w-xl flex-wrap items-center justify-center gap-x-5 gap-y-1 border-y border-[#dce5dc] py-3 text-sm font-semibold text-[#17613a]"><span>{webinarDate.date}</span><span aria-hidden="true" className="hidden text-[#a1b7aa] sm:inline">•</span><span>{webinarDate.time} {formatTimezone(webinar.timezone)}</span></div><div className="mx-auto mt-6 max-w-xl rounded-2xl bg-white p-5 text-left shadow-[0_8px_24px_rgba(45,35,20,0.09)] ring-1 ring-stone-200 sm:p-7"><h2 className="text-center text-xl font-bold sm:text-2xl">Register for the webinar</h2><p className="mt-1 text-center text-sm text-[#59635d]">Save your seat and we’ll send the join link to your inbox.</p><WebinarRegistrationForm slug={slug} /></div></section></div><footer className="bg-[#0f542f] px-5 py-6 text-white"><div className="mx-auto flex max-w-5xl items-center gap-4"><Image alt="FlockFront" height={236} src="/branding/flockfront-logo-final-cropped.png" width={1549} className="w-32 brightness-0 invert" /><span className="border-l border-white/40 pl-4 text-sm">The all-in-one platform for poultry sellers.</span></div></footer></main>; }

function formatWebinarDate(value: string, timezone: string) { const date = new Intl.DateTimeFormat("en-US", { weekday: "long", month: "short", day: "numeric", year: "numeric", timeZone: timezone }).format(new Date(value)); const time = new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit", timeZone: timezone }).format(new Date(value)); return { date, time }; }

function formatTimezone(timezone: string) { const labels: Record<string, string> = { "America/Denver": "Mountain Time", "America/Chicago": "Central Time", "America/New_York": "Eastern Time", "America/Los_Angeles": "Pacific Time" }; return labels[timezone] ?? timezone.replace(/^America\//, "").replace(/_/g, " ") + " Time"; }
