"use client";
import { useState } from "react";
import { publicSupabase } from "@/lib/public-supabase";

const businessTypes = ["Small farm / breeder", "Hatchery", "Poultry reseller / dealer", "Farm store / feed store", "Other"];
const birdRanges = ["0–5", "6–25", "26–100", "101–1,000", "1,000+"];
const referrals = ["Search engine", "Social media", "Friend or colleague", "FlockFront customer", "Other"];

export function WebinarRegistrationForm({ slug }: { slug: string }) { const [form, setForm] = useState({ first_name: "", last_name: "", email: "", business_type: "", annual_birds_sold: "", referral_source: "" }); const [state, setState] = useState<"idle" | "submitting" | "success">("idle"); const [error, setError] = useState<string | null>(null); const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setState("submitting"); const { error: invokeError } = await publicSupabase.functions.invoke("webinar-register", { body: { slug, ...form, referral_source: form.referral_source || null } }); if (invokeError) { const message = invokeError.message.includes("already_registered") ? "You’re already registered for this webinar." : "We couldn’t complete your registration. Please check your details and try again."; setError(message); setState("idle"); return; } setState("success"); }
  if (state === "success") return <div className="mt-7 rounded-xl bg-[#edf7ed] p-6 text-center"><h3 className="text-xl font-bold text-[#155c32]">You’re registered!</h3><p className="mt-2 text-sm leading-6 text-[#3f5145]">Check your inbox for the webinar confirmation and Zoom link.</p></div>;
  return <form className="mt-7 grid gap-4" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" value={form.first_name} onChange={(v) => update("first_name", v)} required /><Field label="Last name" value={form.last_name} onChange={(v) => update("last_name", v)} required /></div><Field label="Email address" type="email" value={form.email} onChange={(v) => update("email", v)} required /><Select label="What best describes your poultry business?" value={form.business_type} options={businessTypes} onChange={(v) => update("business_type", v)} required /><Select label="How many birds do you sell per year?" value={form.annual_birds_sold} options={birdRanges} onChange={(v) => update("annual_birds_sold", v)} required /><Select label="How did you hear about FlockFront? (optional)" value={form.referral_source} options={referrals} onChange={(v) => update("referral_source", v)} /><p aria-live="polite" className="text-sm text-red-700">{error}</p><button className="min-h-12 rounded-md bg-[#17613a] px-4 text-base font-bold text-white transition hover:bg-[#124d2e] disabled:opacity-60" disabled={state === "submitting"} type="submit">{state === "submitting" ? "Registering…" : "Register Now"}</button><p className="text-center text-xs text-[#68736b]">We’ll only use your information for this webinar and related FlockFront communication.</p></form>; }
function Field({ label, value, onChange, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="grid gap-1 text-sm font-semibold text-[#202b24]">{label}{required ? <span className="sr-only"> required</span> : null}<input className="rounded-md border border-stone-300 px-3 py-3 font-normal" type={type} value={value} onChange={(e) => onChange(e.target.value)} required={required} /></label>; }
function Select({ label, value, options, onChange, required }: { label: string; value: string; options: string[]; onChange: (value: string) => void; required?: boolean }) { return <label className="grid gap-1 text-sm font-semibold text-[#202b24]">{label}<select className="rounded-md border border-stone-300 bg-white px-3 py-3 font-normal" value={value} onChange={(e) => onChange(e.target.value)} required={required}><option value="">Select one…</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
